# Generated by Django 3.1.6 on 2021-03-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='end_date',
            new_name='End_date',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='start_date',
            new_name='Start_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner_dog',
        ),
        migrations.AddField(
            model_name='car',
            name='id_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner'),
        ),
        migrations.AlterField(
            model_name='drivinglicense',
            name='id_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner'),
        ),
    ]
