# Generated by Django 3.1.6 on 2021-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20210308_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Brand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Colour',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Model',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
