# Generated by Django 3.1.6 on 2021-03-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverid',
            old_name='ID_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='driverid',
            old_name='carOwner_driverID',
            new_name='id_owner',
        ),
        migrations.RenameField(
            model_name='possession',
            old_name='car_possession',
            new_name='id_car',
        ),
        migrations.RenameField(
            model_name='possession',
            old_name='carOwner_possession',
            new_name='id_owner',
        ),
        migrations.AddField(
            model_name='carowner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverid',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='possession',
            name='begin_time',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='possession',
            name='end_time',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
