# Generated by Django 3.1.6 on 2021-03-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_remove_carowner_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverid',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='possession',
            name='begin_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='possession',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
