# Generated by Django 3.1.6 on 2021-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_auto_20210309_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
