# Generated by Django 3.1.7 on 2021-03-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_auto_20210327_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='passport_number',
            field=models.DecimalField(decimal_places=0, default=111111, max_digits=6),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='username',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
