# Generated by Django 3.1.7 on 2021-03-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0008_auto_20210327_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
