# Generated by Django 3.1.7 on 2021-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0009_auto_20210327_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='last_login',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
