# Generated by Django 3.1.7 on 2021-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0012_auto_20210327_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
