# Generated by Django 3.1.7 on 2021-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0014_auto_20210327_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
