# Generated by Django 3.1.7 on 2021-03-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0015_auto_20210327_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
