# Generated by Django 3.1.7 on 2021-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0018_auto_20210327_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
