# Generated by Django 3.1.7 on 2021-03-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0026_auto_20210327_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='home_address',
            field=models.TextField(default='address'),
        ),
        migrations.AddField(
            model_name='carowner',
            name='nationality',
            field=models.TextField(default='nationality'),
        ),
        migrations.AddField(
            model_name='carowner',
            name='passport_number',
            field=models.DecimalField(decimal_places=0, default=100000, max_digits=6),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
