# Generated by Django 3.2.4 on 2021-06-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_auto_20210618_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='mentor',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Администратор'), ('1', 'Капитан'), ('2', 'Жюри')], max_length=1),
        ),
    ]
