# Generated by Django 3.2.4 on 2021-06-21 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0004_auto_20210621_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
