# Generated by Django 3.2.4 on 2021-06-21 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0005_alter_team_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='jury',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='score',
            field=models.FloatField(max_length=2, null=True),
        ),
    ]
