# Generated by Django 3.2.4 on 2021-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0007_solution_checkdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='checkDate',
            field=models.DateField(null=True),
        ),
    ]
