# Generated by Django 3.1.7 on 2021-05-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('idAdress', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=20, verbose_name='District')),
                ('street', models.CharField(max_length=20, verbose_name='Street')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('servNumb', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Service number')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone number')),
                ('firstName', models.CharField(max_length=20, verbose_name='First name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Patronymic')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('passport', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name="Person's passport")),
                ('privilege', models.FloatField(verbose_name="Person's privilege")),
                ('firstName', models.CharField(max_length=20, verbose_name='First name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Patronymic')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('idBuilding', models.IntegerField(primary_key=True, serialize=False)),
                ('buildingNumb', models.IntegerField(verbose_name='Number of building')),
                ('building', models.IntegerField(verbose_name='Corps')),
                ('idAdress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity_accounting_app.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('idFlat', models.IntegerField(primary_key=True, serialize=False)),
                ('flatType', models.CharField(max_length=30, verbose_name='Flat type')),
                ('eStove', models.BooleanField(verbose_name='Availability of electric stove')),
                ('peopleCount', models.IntegerField(max_length=2, verbose_name='People count')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity_accounting_app.house')),
            ],
        ),
        migrations.CreateModel(
            name='Bypass',
            fields=[
                ('bypassNumb', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Bypass number')),
                ('dateOfBypass', models.DateField(verbose_name='Bypass date')),
                ('status', models.CharField(choices=[('st1', 'completed'), ('st2', 'uncompleted')], default='st2', max_length=3, verbose_name='Bypass status')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Comment')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity_accounting_app.flat')),
                ('inspectorServNumb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity_accounting_app.inspector')),
            ],
        ),
    ]
