# Generated by Django 3.1.7 on 2021-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='idAdress',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='bypassNumb',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Bypass number'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='peopleCount',
            field=models.IntegerField(verbose_name='People count'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='servNumb',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Service number'),
        ),
    ]
