# Generated by Django 3.1.7 on 2021-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting_app', '0003_flat_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='idRenter',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='eStove',
            field=models.CharField(choices=[('eSt1', 'Is present'), ('eSt2', "Isn't present")], default='eSt2', max_length=4, verbose_name='Availability of electric stove'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='passport',
            field=models.CharField(max_length=12, verbose_name="Person's passport"),
        ),
    ]
