# Generated by Django 3.1.7 on 2021-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting_app', '0006_auto_20210620_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='surname',
        ),
        migrations.AlterField(
            model_name='inspector',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
