# Generated by Django 3.1.7 on 2021-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting_app', '0008_auto_20210620_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='password',
            field=models.CharField(max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='servNumb',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Service number'),
        ),
    ]
