# Generated by Django 3.1.7 on 2021-06-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting_app', '0009_auto_20210620_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='servNumb',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Service number'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Username'),
        ),
    ]
