# Generated by Django 3.1.7 on 2021-06-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting_app', '0011_auto_20210620_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ['idAdress']},
        ),
        migrations.AlterModelOptions(
            name='bypass',
            options={'ordering': ['bypassNumb']},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['idFlat']},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['idBuilding']},
        ),
        migrations.AlterModelOptions(
            name='inspector',
            options={'ordering': ['servNumb']},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ['idRenter']},
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='_password',
        ),
    ]
