# Generated by Django 3.1.7 on 2021-06-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting_app', '0012_auto_20210621_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
