# Generated by Django 3.1.7 on 2021-03-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='Birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='drivinglicense',
            name='Date_of_issue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='End_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='Start_date',
            field=models.DateField(),
        ),
    ]
