# Generated by Django 3.1.7 on 2021-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, through='project_first_app.Own', to='project_first_app.Car'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
