# Generated by Django 3.2.3 on 2021-05-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
