# Generated by Django 3.2.3 on 2021-06-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='img',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_global',
        ),
    ]
