# Generated by Django 3.1.7 on 2021-03-23 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='autoowner',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 12, 59, 1, 929546)),
        ),
    ]
