# Generated by Django 3.1.7 on 2021-03-16 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='ownerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='carId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='ownerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner'),
            preserve_default=False,
        ),
    ]
