# Generated by Django 3.2.3 on 2021-05-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_service_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='preview',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.TextField(),
        ),
    ]
