# Generated by Django 3.2.3 on 2021-05-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210530_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='preview',
            field=models.ImageField(max_length=255, upload_to='img/service/'),
        ),
    ]
