# Generated by Django 3.1.6 on 2021-04-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_owner_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default='admin@gmail.com', max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(default='admin', max_length=40),
        ),
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(default='admin', max_length=16),
        ),
    ]
