# Generated by Django 3.1.6 on 2021-04-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_auto_20210404_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
    ]
