# Generated by Django 3.1.6 on 2021-04-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0006_auto_20210404_2008'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
            ],
        ),
    ]
