# Generated by Django 3.1.6 on 2021-04-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0007_auto_20210404_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
