# Generated by Django 3.1.6 on 2021-04-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0009_auto_20210404_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='cars',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Car'),
        ),
    ]
