# Generated by Django 3.1.6 on 2021-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0012_owner_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$216000$adT8u91SvCpo$kV3TG+/SyvnxVEU1TON07JQXOyksbI5Lpk+llz3eKM8=', max_length=200),
        ),
    ]
