# Generated by Django 3.1.6 on 2021-04-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='owner',
        ),
        migrations.AddField(
            model_name='ownership',
            name='autos',
            field=models.ManyToManyField(to='project_first_app.Auto'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='owners',
            field=models.ManyToManyField(to='project_first_app.Owner'),
        ),
    ]
