# Generated by Django 3.2 on 2021-04-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20210316_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='car_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car'),
        ),
    ]
