# Generated by Django 3.2 on 2021-04-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20210406_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(through='project_first_app.OwnerShip', to='project_first_app.Car'),
        ),
    ]
