# Generated by Django 3.1.6 on 2021-02-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_number', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('getdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('borndate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='owning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('car_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.card')),
                ('owner_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.owner')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='owner_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.owner'),
        ),
    ]
