# Generated by Django 3.1.6 on 2021-03-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owning',
            name='car_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.car'),
        ),
    ]
