# Generated by Django 3.1.7 on 2021-03-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='bith_date',
        ),
        migrations.AddField(
            model_name='carowner',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_issue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='own',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
