# Generated by Django 3.1.6 on 2021-03-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('mark', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='autoOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.auto')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.autoowner')),
            ],
        ),
        migrations.CreateModel(
            name='driverDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=10)),
                ('document_type', models.CharField(max_length=10)),
                ('document_date', models.DateField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.autoowner')),
            ],
        ),
    ]
