# Generated by Django 3.1.7 on 2021-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logach_1', '0002_auto_20210605_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiktask',
            name='answer',
            field=models.JSONField(default=dict),
        ),
    ]
