# Generated by Django 3.1.7 on 2021-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logach_1', '0004_auto_20210605_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, upload_to='logach_back\\logach_screens'),
        ),
    ]
