# Generated by Django 3.1.7 on 2021-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logach_1', '0005_auto_20210605_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiktask',
            name='solved',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('2', 'None')], max_length=1),
        ),
    ]
