# Generated by Django 3.1.7 on 2021-06-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logach_1', '0006_auto_20210605_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
