# Generated by Django 3.1.7 on 2021-06-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logach_1', '0007_remove_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AlterField(
            model_name='logiktask',
            name='answer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logiktask',
            name='solved',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=1),
        ),
    ]
