# Generated by Django 3.1.7 on 2021-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('volume', models.IntegerField(null=True)),
                ('orig_lang', models.CharField(max_length=2)),
                ('kind', models.CharField(max_length=10)),
                ('discipline', models.TextField(blank=True, null=True)),
                ('publish_place', models.TextField()),
                ('publish_year', models.IntegerField()),
                ('code', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookCompiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'BookCompiler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('inv_number', models.CharField(max_length=8, unique=True)),
                ('storage_room', models.IntegerField()),
                ('storage_rack', models.IntegerField()),
                ('storage_shelf', models.IntegerField()),
                ('price', models.IntegerField()),
                ('withdrawal_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
            options={
                'db_table': 'BookCopy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('patronymic', models.TextField()),
                ('birthdate', models.DateField()),
                ('address', models.TextField()),
                ('telnumber', models.CharField(max_length=12)),
                ('card_num', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'db_table': 'Borrower',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Compiler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'Publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Translator',
                'managed': False,
            },
        ),
    ]
