# Generated by Django 3.1.7 on 2021-06-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRevision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('publish_place', models.TextField()),
                ('publish_year', models.IntegerField()),
                ('code', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'BookRevision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('withdrawal_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
            options={
                'db_table': 'Borrow',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BookCompiler',
        ),
        migrations.CreateModel(
            name='RevisionCompiler',
            fields=[
                ('book_rev', models.ForeignKey(db_column='book_rev', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elibrary.bookrevision')),
            ],
            options={
                'db_table': 'RevisionCompiler',
                'managed': False,
            },
        ),
    ]
