# Generated by Django 3.1.6 on 2021-03-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nmstr1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possesion',
            name='id_carOwner',
        ),
        migrations.AddField(
            model_name='possesion',
            name='id_Car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nmstr1.car'),
        ),
        migrations.AddField(
            model_name='possesion',
            name='id_CarOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nmstr1.car_owner'),
        ),
    ]
