# Generated by Django 3.1.6 on 2021-04-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210302_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='cars',
            field=models.ManyToManyField(through='blog.owning', to='blog.car'),
        ),
    ]
