# Generated by Django 3.1.7 on 2021-03-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_number', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(max_length=30, null=True, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('date_of_birth', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateTimeField()),
                ('expiration_date', models.DateTimeField(null=True)),
                ('id_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.car')),
                ('id_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.owner')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_license', models.CharField(max_length=10, verbose_name='Номер лицензии')),
                ('type', models.CharField(max_length=10, verbose_name='Тип')),
                ('date_of_issue', models.DateTimeField()),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.owner')),
            ],
        ),
    ]
