# Generated by Django 2.2.12 on 2021-02-10 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20210210_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='carownership',
            name='date_of_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carownership',
            name='date_of_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
