# Generated by Django 3.1.6 on 2021-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20210210_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(through='project_first_app.CarOwnership', to='project_first_app.Car'),
        ),
    ]
