# Generated by Django 3.1.7 on 2021-04-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_owner',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car_owner',
            name='home_address',
            field=models.CharField(default='Grinvich', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car_owner',
            name='nationality',
            field=models.CharField(default='pupil', max_length=40, null=True),
        ),
    ]
