# Generated by Django 3.1.7 on 2021-04-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_project_app', '0002_auto_20210406_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_owner',
            name='passport_number',
            field=models.CharField(default='999999', max_length=6),
        ),
    ]
