# Generated by Django 3.2.3 on 2021-06-12 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=45)),
                ('reg_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('exp_start', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(max_length=45)),
                ('liter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MotorDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(default=datetime.date.today)),
                ('point_of_loading', models.CharField(max_length=255)),
                ('point_if_unloading', models.CharField(max_length=255)),
                ('mileage_total', models.IntegerField()),
                ('mileage_cargo', models.IntegerField()),
                ('consignor', models.CharField(max_length=255)),
                ('consignee', models.CharField(max_length=255)),
                ('id_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autobase_app.car')),
                ('id_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autobase_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.FloatField()),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autobase_app.car')),
                ('id_fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autobase_app.fuel')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('motor_depot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autobase_app.motordepot')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='garage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autobase_app.garage'),
        ),
        migrations.AddField(
            model_name='car',
            name='refuels',
            field=models.ManyToManyField(through='autobase_app.Refuel', to='autobase_app.Fuel'),
        ),
    ]
