# Generated by Django 3.2.3 on 2021-06-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobase_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='order_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
