# Generated by Django 3.1.7 on 2021-05-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIBDD_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
