# Generated by Django 3.1.7 on 2021-05-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIBDD_app', '0002_auto_20210531_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchinfo',
            name='reasons',
            field=models.TextField(blank=True),
        ),
    ]
