# Generated by Django 3.1.7 on 2021-03-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=15)),
                ('mark', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Date_of_Birth', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='driver_license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license_id', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date_of_receipt', models.DateTimeField()),
                ('CarOwner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.CarOwner')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('auto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.auto')),
                ('CarOwner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.CarOwner')),
            ],
        ),
        migrations.AddField(
            model_name='CarOwner',
            name='CarOwnerships',
            field=models.ManyToManyField(through='project_first_app.CarOwnership', to='project_first_app.auto'),
        ),
    ]
