# Generated by Django 3.1.7 on 2021-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20210319_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='CarOwner',
            old_name='Citizenship',
            new_name='citizenship',
        ),
        migrations.RenameField(
            model_name='CarOwner',
            old_name='Adress_of_Home',
            new_name='home_adress',
        ),
        migrations.RemoveField(
            model_name='CarOwner',
            name='Passport_number',
        ),
        migrations.AddField(
            model_name='CarOwner',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
