# Generated by Django 3.2.4 on 2021-06-12 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2021, 6, 12, 17, 34, 43, 784434)),
        ),
        migrations.AlterField(
            model_name='usage',
            name='day',
            field=models.DateField(default=datetime.datetime(2021, 6, 12, 17, 34, 43, 784434)),
        ),
    ]
