# Generated by Django 3.2.4 on 2021-06-14 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideApp', '0002_auto_20210612_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2021, 6, 14, 15, 29, 26, 264832)),
        ),
        migrations.AlterField(
            model_name='usage',
            name='day',
            field=models.DateField(default=datetime.datetime(2021, 6, 14, 15, 29, 26, 264832)),
        ),
    ]
