# Generated by Django 3.2.3 on 2021-06-11 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='supply_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 12, 14, 49, 490866)),
        ),
    ]
