# Generated by Django 3.2.4 on 2021-06-19 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('1', 'Rings'), ('2', 'Earrings'), ('3', 'Chains'), ('4', 'Bracelets'), ('5', 'Pendants'), ('6', 'Necklace'), ('7', 'Charms'), ('8', 'Another')], default='8', max_length=10)),
                ('num', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patr', models.CharField(max_length=30)),
                ('birth', models.DateField()),
                ('salary', models.PositiveIntegerField(default=0)),
                ('exp', models.PositiveSmallIntegerField(default=0)),
                ('address', models.CharField(max_length=45)),
                ('education', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_fantasy_app.factory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_fantasy_app.production')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 6, 19))),
                ('price', models.PositiveIntegerField()),
                ('num', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_fantasy_app.production')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_fantasy_app.seller')),
            ],
        ),
    ]
