# Generated by Django 3.1.7 on 2021-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='state_Name',
            new_name='state_number',
        ),
        migrations.AlterField(
            model_name='carowner',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='date_of_issue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='date_sale',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='date_start',
            field=models.DateField(),
        ),
    ]
