# Generated by Django 3.1.7 on 2021-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20210221_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
