# Generated by Django 3.1.7 on 2021-02-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_license'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car',
        ),
        migrations.DeleteModel(
            name='license',
        ),
        migrations.DeleteModel(
            name='owner',
        ),
    ]
