# Generated by Django 3.1.6 on 2021-04-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PassportNumber',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
