# Generated by Django 3.1.6 on 2021-04-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0006_auto_20210413_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='BirthDate',
            field=models.DateTimeField(),
        ),
    ]
