# Generated by Django 3.1.6 on 2021-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app_zemlyakov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ownerships',
            field=models.ManyToManyField(through='project_app_zemlyakov.Ownership', to='project_app_zemlyakov.CarOwner'),
        ),
    ]
