# Generated by Django 3.1.7 on 2021-03-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Color',
            field=models.CharField(max_length=30),
        ),
    ]
