# Generated by Django 3.1.7 on 2021-03-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='cars',
        ),
    ]
