# Generated by Django 3.1.7 on 2021-03-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='adress',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
