# Generated by Django 3.2.3 on 2021-05-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preview', models.CharField(max_length=255)),
                ('project_url', models.CharField(max_length=255, null=True)),
                ('code_url', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
