# Generated by Django 3.2.3 on 2021-05-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(upload_to=''),
        ),
    ]
