# Generated by Django 3.2.3 on 2021-05-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(max_length=255, upload_to='img/projects/'),
        ),
    ]
