# Generated by Django 3.2.3 on 2021-05-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
