# Generated by Django 3.2.3 on 2021-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210531_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='img/projects/'),
        ),
    ]
