# Generated by Django 3.2 on 2021-05-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_FIO', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO_client', models.CharField(max_length=50)),
                ('passport_number', models.IntegerField()),
                ('date_of_passport_start', models.DateField()),
                ('registration_number', models.IntegerField()),
                ('who_give_the_passport', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_flight_start', models.DateTimeField()),
                ('time_flight_finish', models.DateTimeField()),
                ('date_flight_start', models.DateField()),
                ('date_flight_finish', models.DateField()),
                ('name_of_flight', models.CharField(max_length=20)),
                ('airport_start', models.CharField(max_length=40)),
                ('airport_finish', models.CharField(max_length=40)),
                ('type_of_flight', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plane_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_office_adress', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transit_boarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_airport', models.CharField(max_length=20)),
                ('date_flight_start', models.DateField()),
                ('date_flight_finish', models.DateField()),
                ('time_flight_start', models.DateTimeField()),
                ('time_flight_finish', models.DateTimeField()),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('ticket_status', models.CharField(max_length=20)),
                ('ticket_class', models.CharField(max_length=20)),
                ('ticket_number', models.IntegerField()),
                ('cashier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cashier')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_position', models.CharField(max_length=50)),
                ('employee_FIO', models.CharField(max_length=60)),
                ('people', models.ManyToManyField(through='blog.Crew', to='blog.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date_of_check', models.DateField()),
                ('made_year', models.DateField()),
                ('plane_type', models.CharField(max_length=20)),
                ('plane_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plane_type')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=20)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.client')),
                ('ticket_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='board_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plane'),
        ),
        migrations.AddField(
            model_name='flight',
            name='ticket_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ticket'),
        ),
        migrations.AddField(
            model_name='crew',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.flight'),
        ),
        migrations.AddField(
            model_name='crew',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.staff'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='ticket_office_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ticket_office'),
        ),
    ]
