# Generated by Django 3.2.4 on 2021-06-23 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_fantasy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 23)),
        ),
    ]
