# Generated by Django 3.1.7 on 2021-03-28 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210328_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoowner',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 18, 31, 43, 154669)),
        ),
    ]
