# Generated by Django 3.1.7 on 2021-03-31 15:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210328_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoowner',
            old_name='id_auto',
            new_name='auto',
        ),
        migrations.RenameField(
            model_name='autoowner',
            old_name='id_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='id_owner',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='auto',
            name='owner',
            field=models.ManyToManyField(through='first_app.AutoOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autoowner',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 18, 31, 44, 216645)),
        ),
    ]
