# Generated by Django 3.1.7 on 2021-03-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20210302_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowning',
            name='begin_date',
            field=models.DateTimeField(),
        ),
    ]
