# Generated by Django 3.1.7 on 2021-03-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoowner',
            name='has',
            field=models.ManyToManyField(through='project_first_app.Owning', to='project_first_app.Auto'),
        ),
    ]
