# Generated by Django 3.1.7 on 2021-04-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_autoowner_has'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoowner',
            old_name='has',
            new_name='ownership',
        ),
    ]
