# Generated by Django 3.2.5 on 2021-07-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id_post_office', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number_office', models.IntegerField(unique=True, verbose_name='Номер отделения')),
                ('address_office', models.CharField(max_length=75, verbose_name='Адрес отделения')),
            ],
        ),
    ]
