# Generated by Django 3.2.5 on 2021-07-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0002_editorialoffice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id_newspaper', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title_newspaper', models.CharField(max_length=75, verbose_name='Название газеты')),
                ('cost_newspaper', models.IntegerField(verbose_name='Цена экземпляра')),
                ('publication_index', models.IntegerField(null=True, verbose_name='Индекс издания')),
                ('number_office', models.IntegerField(null=True, verbose_name='Номер отделения')),
                ('date_of_issue', models.DateField(null=True, verbose_name='Дата выпуска')),
                ('id_post_office_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.postoffice', verbose_name='Почтовое отделение (FK)')),
            ],
        ),
    ]
