# Generated by Django 3.2.5 on 2021-07-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0003_newspaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название статьи')),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperDistribution',
            fields=[
                ('id_newspaper_distribution', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number_of_copies', models.IntegerField(null=True, verbose_name='Цена экземпляра')),
                ('cost_release', models.IntegerField(null=True, verbose_name='Цена экземпляра')),
                ('id_post_office_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.postoffice', verbose_name='Почтовое отделение (FK)')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingOffice',
            fields=[
                ('id_printing_office', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_printing_office', models.CharField(max_length=75, verbose_name='Название типографии')),
                ('address_printing_office', models.CharField(max_length=75, null=True, verbose_name='Адрес типографии')),
                ('count', models.IntegerField(null=True, verbose_name='Тираж')),
                ('schedule_printing_office', models.CharField(max_length=75, null=True, verbose_name='График работы')),
                ('id_newspaper_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.newspaper', verbose_name='Газета (FK)')),
                ('post_office', models.ManyToManyField(through='newspaper_app.NewspaperDistribution', to='newspaper_app.PostOffice')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id_release', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_of_issue_release', models.DateField(verbose_name='Дата выпуска')),
                ('publication_index_release', models.IntegerField(null=True, verbose_name='Индекс издания')),
                ('cost_copy', models.IntegerField(null=True, verbose_name='Цена экземпляра')),
                ('id_newspaper_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.newspaper', verbose_name='Газета (FK)')),
                ('id_printing_office_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.printingoffice', verbose_name='Типография (FK)')),
            ],
        ),
        migrations.AddField(
            model_name='newspaperdistribution',
            name='id_printing_office_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.printingoffice', verbose_name='Типография (FK)'),
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id_correction', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=150, null=True, verbose_name='Содержание правки')),
                ('id_article_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.article', verbose_name='Статья (FK)')),
                ('id_editorial_office_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.editorialoffice', verbose_name='Редакция (FK)')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='id_release_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.release', verbose_name='Выпуск (FK)'),
        ),
    ]
