# Generated by Django 3.2.5 on 2021-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0004_auto_20210702_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingoffice',
            name='id_newspaper_fk',
        ),
        migrations.AddField(
            model_name='printingoffice',
            name='id_newspaper_fk',
            field=models.ManyToManyField(to='newspaper_app.Newspaper', verbose_name='Газеты (FK)'),
        ),
        migrations.AlterField(
            model_name='printingoffice',
            name='post_office',
            field=models.ManyToManyField(null=True, through='newspaper_app.NewspaperDistribution', to='newspaper_app.PostOffice'),
        ),
    ]
