# Generated by Django 3.2.5 on 2021-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0005_auto_20210702_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingoffice',
            name='id_newspaper_fk',
            field=models.ManyToManyField(to='newspaper_app.Newspaper', verbose_name='Газета (FK)'),
        ),
    ]
