# Generated by Django 3.2.5 on 2021-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0006_alter_printingoffice_id_newspaper_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingoffice',
            name='post_office',
            field=models.ManyToManyField(through='newspaper_app.NewspaperDistribution', to='newspaper_app.PostOffice'),
        ),
    ]
