# Generated by Django 3.2.2 on 2021-05-11 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('director_surname', models.CharField(max_length=25)),
                ('computer_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_computers', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('registration_number', models.IntegerField()),
                ('year_of_purchase', models.DateField()),
                ('service_life', models.IntegerField()),
                ('hour_online', models.DecimalField(decimal_places=2, max_digits=9)),
                ('hour_game', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField()),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='computer_cafe_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DayResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_online', models.TimeField()),
                ('use_game', models.TimeField()),
                ('sold_game', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sold_online', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.cafe')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.computer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='computer_cafe_app.Order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.cafe')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.cart')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.computer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='computers',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='computer_cafe_app.CartProduct'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.customer'),
        ),
    ]
