# Generated by Django 3.2.2 on 2021-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_cafe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='game_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='online_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='time_order',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayresult',
            name='use_game',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dayresult',
            name='use_online',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
