# Generated by Django 3.2.2 on 2021-05-15 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computer_cafe_app', '0002_auto_20210515_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_order',
        ),
        migrations.AddField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.cafe'),
        ),
        migrations.AddField(
            model_name='order',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computer_cafe_app.computer'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
