# Generated by Django 3.2.2 on 2021-05-15 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_cafe_app', '0003_auto_20210515_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 5, 15)),
        ),
    ]
