# Generated by Django 3.2.2 on 2021-05-17 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_cafe_app', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
    ]
