# Generated by Django 3.1.7 on 2021-03-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_of_issue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='owning',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='owning',
            name='start_date',
            field=models.DateField(),
        ),
    ]
