# Generated by Django 3.2.4 on 2021-06-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climber',
            fields=[
                ('climber_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('climber_name', models.CharField(max_length=75, verbose_name='Имя')),
                ('climber_surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('climber_age', models.IntegerField(verbose_name='Возраст')),
                ('climber_xp', models.IntegerField(verbose_name='Опыт')),
                ('climber_address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('club_name', models.CharField(max_length=75, verbose_name='Название')),
                ('club_city', models.CharField(max_length=100, verbose_name='Город')),
                ('club_mail', models.EmailField(max_length=75, verbose_name='Почта')),
                ('club_phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('country', models.CharField(max_length=75, verbose_name='Страна')),
                ('club_contact_person', models.CharField(max_length=75, verbose_name='Связь')),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('mountain_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mountain_name', models.CharField(max_length=75, verbose_name='Название горы')),
                ('mountain_hight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Высота горы')),
                ('country', models.CharField(max_length=75, verbose_name='Срана')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=75, verbose_name='Название')),
                ('group_creation_date', models.DateField(max_length=100, verbose_name='Дата создания')),
                ('climber', models.ManyToManyField(related_name='climbers', to='Climbers.Climber', verbose_name='Участники')),
            ],
        ),
        migrations.CreateModel(
            name='Climbing',
            fields=[
                ('climbing_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('climbing_start', models.DateField(verbose_name='Старт')),
                ('climbing_finish', models.DateField(verbose_name='Финиш')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Climbers.group', verbose_name='Группа')),
            ],
        ),
        migrations.AddField(
            model_name='climber',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Climbers.club', verbose_name='Клуб'),
        ),
    ]
