# Generated by Django 3.2.4 on 2021-06-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Climbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbing',
            name='mountain',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='Climbers.climber', verbose_name='Вершина'),
            preserve_default=False,
        ),
    ]
