# Generated by Django 3.2.4 on 2021-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climbers', '0002_climbing_mountain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountain',
            old_name='mountain_hight',
            new_name='mountain_high',
        ),
        migrations.AlterField(
            model_name='club',
            name='club_contact_person',
            field=models.CharField(max_length=75, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=75, unique=True, verbose_name='Название'),
        ),
    ]
