# Generated by Django 3.2.4 on 2021-06-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Climbers', '0005_alter_climbing_mountain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbing',
            name='mountain',
        ),
        migrations.AddField(
            model_name='climbing',
            name='waypoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Climbers.waypoint', verbose_name='Вершина'),
            preserve_default=False,
        ),
    ]
