# Generated by Django 3.2.4 on 2021-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climbers', '0006_auto_20210613_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbing',
            name='status',
            field=models.CharField(choices=[('plan', 'Планируется'), ('in_process', 'В процессе'), ('end', 'Завершен')], default='plan', max_length=20, verbose_name='Статус'),
        ),
    ]
