# Generated by Django 3.2.4 on 2021-06-14 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Climbers', '0007_climbing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbing',
            name='status',
            field=models.CharField(choices=[('Планируется', 'Планируется'), ('В процессе', 'В процессе'), ('Завершен', 'Завершен')], default='plan', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_creation_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=100, verbose_name='Дата создания'),
        ),
    ]
