# Generated by Django 3.2.4 on 2021-06-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Climbers', '0009_alter_climbing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySituation',
            fields=[
                ('emergency_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('desc', models.TextField(verbose_name='Описание')),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Climbers.climber', verbose_name='Альпинист')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Climbers.group', verbose_name='Группа')),
            ],
        ),
    ]
