# Generated by Django 3.2.4 on 2021-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climbers', '0010_emergencysituation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencysituation',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='emergency',
            field=models.ManyToManyField(null=True, to='Climbers.EmergencySituation', verbose_name='Нештатные ситуации'),
        ),
    ]
