# Generated by Django 3.2.3 on 2021-05-24 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atricles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Статья')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('type', models.CharField(max_length=63, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.generate_imageset_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
