# Generated by Django 3.2.3 on 2021-05-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_atricles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atricles',
            name='type',
            field=models.CharField(choices=[('HIS', 'Исторические'), ('LIT', 'Литературные')], max_length=3, verbose_name='Тип'),
        ),
    ]
