# Generated by Django 3.2.3 on 2021-05-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_writer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atricles',
            old_name='title',
            new_name='article_title',
        ),
    ]
