# Generated by Django 3.2.3 on 2021-05-24 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_rename_title_atricles_article_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atricles',
            new_name='Articles',
        ),
    ]
