# Generated by Django 3.2.3 on 2021-05-24 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_rename_atricles_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEF', 'Книги'), ('PRS', 'Проза')], max_length=3, verbose_name='Тип')),
                ('author', models.TextField(verbose_name='Автор')),
                ('title', models.TextField(verbose_name='Название')),
                ('date', models.TextField(verbose_name='Дата написания')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('anatation', models.TextField(verbose_name='Аннотация')),
                ('plus_rating', models.IntegerField(verbose_name='Аннотация')),
                ('minus_rating', models.IntegerField(verbose_name='Аннотация')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.generate_imageset_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
