# Generated by Django 3.2.3 on 2021-05-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
