# Generated by Django 3.2.3 on 2021-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_books_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='chapters',
            field=models.IntegerField(default=12, verbose_name='Количество глав'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='words',
            field=models.IntegerField(default=23, verbose_name='Количество слов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='minus_rating',
            field=models.IntegerField(verbose_name='Отрицательный рейтинг'),
        ),
        migrations.AlterField(
            model_name='books',
            name='plus_rating',
            field=models.IntegerField(verbose_name='Положительный рейтинг'),
        ),
    ]
