# Generated by Django 3.2.3 on 2021-05-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210525_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='text',
            field=models.TextField(default=12, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
