# Generated by Django 3.2.3 on 2021-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210527_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='bibliografi',
            field=models.TextField(default=2, verbose_name='Библиография'),
            preserve_default=False,
        ),
    ]
