# Generated by Django 3.2.3 on 2021-05-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_writer_about_life'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='user',
        ),
    ]
