# Generated by Django 3.2.3 on 2021-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_writer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='chapters',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество глав'),
        ),
        migrations.AlterField(
            model_name='books',
            name='words',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество слов'),
        ),
    ]
