# Generated by Django 3.2.3 on 2021-05-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210528_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата написания'),
        ),
    ]
