# Generated by Django 3.2.3 on 2021-05-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
