# Generated by Django 3.2.3 on 2021-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_likes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='type',
            field=models.CharField(choices=[('LIK', 'Лайк'), ('DIS', 'Дислайк')], default=2, max_length=3, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
