# Generated by Django 3.2.3 on 2021-05-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_likes_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='text',
        ),
    ]
