# Generated by Django 3.2.3 on 2021-05-30 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_remove_likes_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIK', 'Лайк'), ('DIS', 'Дислайк')], max_length=3, verbose_name='Тип')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.review', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Лайк рецензии',
                'verbose_name_plural': 'Лайки рецинзий',
            },
        ),
    ]
