# Generated by Django 3.2.1 on 2021-05-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20210512_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='standard_code',
            new_name='property',
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
